server:
  port: 8081
  servlet:
    context-path: /api/v1
spring:
  application:
    name: github_service
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: aac8b86d8b4c3b37bf49
            client-secret: 0ef03b31c2d3a674255384c3c6fa47ab5bc3dcbd
            redirect-uri: 'http://25.59.188.46:8081/api/v1/auth/github/callback'
            scope:
              - repo
              - workflow